events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /bio/ {
            # Route requests starting with /bio/ to the bio container
            proxy_pass http://bio:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /port-backend/ {
            # Route requests starting with /app2/ to the app2 container
            proxy_pass http://172.20.0.4:3006/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /port-frontend/ {
            # Route requests starting with /app2/ to the app2 container
            proxy_pass http://172.20.0.5:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /postgres/ {
            # Route requests starting with /app2/ to the app2 container
            proxy_pass http://172.20.0.6:5432/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /network-rt/ {
            # Route requests starting with /app2/ to the app2 container
            proxy_pass http://172.20.0.7:3001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /mobilinq/ {
            # Route requests starting with /app2/ to the app2 container
            proxy_pass http://mobilinq:3002/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /calc-oval/ {
            # Route requests starting with /app2/ to the app2 container
            proxy_pass http://172.20.0.11:3003/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /pyfhir/ {
            # Route requests starting with /app2/ to the app2 container
            proxy_pass http://172.20.0.12:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # You can add a default location for other requests if needed
        location / {
            proxy_pass http://bio:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
