events {
    worker_connections 1024;
}

http {
    server {
        listen 443 ssl http2;

        location /bio/ {
            # Route requests starting with /bio/ to the bio container
            proxy_pass http://bio:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /port-backend/ {
            # Route requests starting with /port-backend/ to the react portfolio backend container
            proxy_pass http://172.20.0.4:3006/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /port-frontend/ {
            # Route requests starting with /port-frontend/ to the react portfolio front end container
            proxy_pass http://172.20.0.5:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /postgres/ {
            # Route requests starting with /postgres/ to the postgres container
            proxy_pass http://172.20.0.6:5432/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /network-rt/ {
            # Route requests starting with /network-rt/ to the network realtime container
            proxy_pass http://172.20.0.7:3001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /mobilinq/ {
            # Route requests starting with /mobilinq/ to the mobilinq container
            proxy_pass http://mobilinq:3002/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /calc-oval/ {
            # Route requests starting with /calc-oval/ to the oval calculator container
            proxy_pass http://172.20.0.11:3003/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /pyfhir/ {
            # Route requests starting with /pyfhir/ to the python fire container
            proxy_pass http://172.20.0.12:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # utilities to push the recreaish 
        location /rec-util/ {
            # Route requests starting with /recreaish/ to the recreaish backend container
            proxy_pass http://172.20.0.14/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /recreaish-dev/ {
            # Route requests starting with /recreaish/ to the recreaish backend container
            proxy_pass http://172.20.0.15/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /recreaish-qa/ {
            # Route requests starting with /recreaish/ to the recreaish backend container
            proxy_pass http://172.20.0.16/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # You can add a default location for other requests if needed
        location / {
            proxy_pass http://bio:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
